trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: CodeCoverageUpload
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --import
      curl -Os https://cli.codecov.io/latest/linux/codecov
      curl -Os https://cli.codecov.io/latest/linux/codecov.SHA256SUM
      curl -Os https://cli.codecov.io/latest/linux/codecov.SHA256SUM.sig
      gpg --verify codecov.SHA256SUM.sig codecov.SHA256SUM
      shasum -a 256 -c codecov.SHA256SUM
      chmod +x codecov
      ./codecov upload-process -f "./$(buildFolderName)/$(testResultFolderName)/JaCoCo_coverage.xml"
    displayName: 'Upload code coverage to Codecov.io'
    env:
      CODECOV_TOKEN: $(CODECOV_TOKEN)
      CODECOV_URL: $(CODECOV_URL)
