trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: PublishCodeCovCoverage
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
      displayName: 'Install Node.js 22'
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: PublishCodeCovCoverage@1
    displayName: 'Upload code coverage to Codecov.io'
    inputs:
      buildFolderName: '$(Build.BinariesDirectory)'
      testResultFolderName: '$(Build.TestResultsDirectory)'
    env:
      CODECOV_TOKEN: $(CODECOV_TOKEN)
      CODECOV_URL: $(CODECOV_URL)
