trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/**
  tags:
    include:
      - 'v*'
    exclude:
      - '*-*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: PublishCodeCovCoverage
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '22.x'
          displayName: 'Install Node.js 22'
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '5.x'
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - script: |
          npm ci
          npm run package
        displayName: 'Run package'
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'junit.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)'
          mergeTestResults: true
          testRunTitle: 'Unit Tests'
        condition: succeededOrFailed()
      - task: PublishCodeCovCoverage@1
        displayName: 'Upload code coverage to Codecov.io'
        inputs:
          testResultFolderName: '$(Build.SourcesDirectory)/coverage'
          verbose: true
        env:
          CODECOV_TOKEN: $(CODECOV_TOKEN)
