name: Build and Test
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Lint production code
        run: npm run lint

      - name: Package
        run: npm run package

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./junit.xml, ./integration-junit.xml
          flags: unit
          fail_ci_if_error: true
          verbose: true

      - name: Upload coverage using our own task
        working-directory: dist/PublishCodeCovCoverageTask
        if: ${{ !cancelled() }}
        run: node index.js
        env:
          # Pass the test result folder name containing coverage files
          # Using absolute path to ensure we're pointing to the right coverage directory
          INPUT_TESTRESULTFOLDERNAME: '${{ github.workspace }}/coverage'
          INPUT_NETWORKROOTFOLDER: '${{ github.workspace }}'
          INPUT_VERBOSE: 'true'
          INPUT_CODECOVTOKEN: '${{ secrets.CODECOV_TOKEN }}'
          INPUT_FLAG: 'unit'
