name: Build and Test
permissions:
  contents: read
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Package
        run: npm run package

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./junit.xml
          flags: unit
          fail_ci_if_error: true
          verbose: true

      - name: Upload coverage using our own task
        if: ${{ !cancelled() }}
        run: |
          # Set the environment variable for the Codecov token
          export CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}

          # Store the workspace root directory
          export WORKSPACE_ROOT=$GITHUB_WORKSPACE

          # Change to the distribution directory with our built task
          cd dist/PublishCodeCovCoverageTask

          # List files in the current directory to verify contents
          ls -la

          # Execute our own task with Node.js to upload the coverage files
          node index.js
        env:
          # Pass the test result folder name containing coverage files
          # Using absolute path to ensure we're pointing to the right coverage directory
          INPUT_TESTRESULTFOLDERNAME: '${{ github.workspace }}/coverage'
          #INPUT_COVERAGEFILENAME: '${{ github.workspace }}/coverage/clover.xml'
          #INPUT_COVERAGEFILENAME: '${{ github.workspace }}/coverage/lcov.info'
          # Enable verbose output for better debugging
          INPUT_VERBOSE: 'true'
